### ISSUE TITLE
Octoprint Continous Print API Error 500 INTERNAL SERVER ERROR after "Start Managing" is pressed.

### ISSUE THREAD

**Issue by JacobDymkowski** [smartin015/continuousprint#128]
I installed continousprint, and whenever I try to start it, I get an Internal Server Error from Octoprint. I am running my octoprint instance off of OctoPi 4a if that makes a difference. Any help would be appreciated.
![Capture41](https://user-images.githubusercontent.com/99190949/195733803-e6a68e96-1ca9-4dd6-9da2-cda61cfd0611.PNG)
[octoprint-systeminfo-20221014000047.zip](https://github.com/smartin015/continuousprint/files/9781388/octoprint-systeminfo-20221014000047.zip)

**Comment by smartin015** [comment]
Thanks for posting the systeminfo bundle - I think I tracked all the errors down to a failure to declare a mutex:

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/octoprint/plugin/__init__.py", line 273, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/octoprint/util/__init__.py", line 1688, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/continuousprint/__init__.py", line 64, in on_after_startup
    self._plugin.start()
  File "/usr/lib/python3.9/site-packages/continuousprint/plugin.py", line 83, in start
    self._init_driver()
  File "/usr/lib/python3.9/site-packages/continuousprint/plugin.py", line 317, in _init_driver
    self.d = dcls(
  File "/usr/lib/python3.9/site-packages/continuousprint/driver.py", line 48, in __init__
    self.mutex = Lock()
  File "/usr/lib/python3.9/multiprocessing/context.py", line 68, in Lock
    return Lock(ctx=self.get_context())
  File "/usr/lib/python3.9/multiprocessing/synchronize.py", line 162, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/usr/lib/python3.9/multiprocessing/synchronize.py", line 57, in __init__
    sl = self._semlock = _multiprocessing.SemLock(
FileNotFoundError: [Errno 2] No such file or directory
```

This does indeed look like an [error related to running on an unsupported OS](https://superfastpython.com/filenotfounderror-multiprocessing-python/) - and I don't know how deep the rabbit hole goes here as I've only been testing/releasing under Linux / RPi. 

This mutex code is essential to running CPQ properly - lots of concurrency problems will happen otherwise. I'm afraid CPQ just isn't going to work on Android, until we find and fix an unknown number of bugs to get it to that point. I'm going to move this to a "support Android" feature request - I've got other priorities for development, but perhaps you can track down someone who'd be willing to add support in the meantime :)
